//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18051
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Client.CustomerService.Framework.UserService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserOnlineStatus", Namespace="http://schemas.datacontract.org/2004/07/Client.Model")]
    public enum UserOnlineStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        离线 = -2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        隐身 = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        忙碌 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        在线 = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatingResult", Namespace="http://schemas.datacontract.org/2004/07/Client.Service.DataContract")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.CustomerService.Framework.UserService.OperatingResultOfArrayOfUserInfoResult5O3_PPRz2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.CustomerService.Framework.UserService.OperatingResultOfstring))]
    public partial class OperatingResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatingResultOfArrayOfUserInfoResult5O3_PPRz2", Namespace="http://schemas.datacontract.org/2004/07/Client.Service.DataContract")]
    public partial class OperatingResultOfArrayOfUserInfoResult5O3_PPRz2 : Client.CustomerService.Framework.UserService.OperatingResult {
        
        private System.Collections.Generic.List<Client.CustomerService.Framework.UserService.UserInfoResult> ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Client.CustomerService.Framework.UserService.UserInfoResult> Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatingResultOfstring", Namespace="http://schemas.datacontract.org/2004/07/Client.Service.DataContract")]
    public partial class OperatingResultOfstring : Client.CustomerService.Framework.UserService.OperatingResult {
        
        private string ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfoResult", Namespace="http://schemas.datacontract.org/2004/07/Client.Service.DataContract")]
    public partial class UserInfoResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Client.CustomerService.Framework.UserService.UserOnlineStatus OnlineStatusField;
        
        private Client.CustomerService.Framework.UserService.UserInfoType TypeField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.CustomerService.Framework.UserService.UserOnlineStatus OnlineStatus {
            get {
                return this.OnlineStatusField;
            }
            set {
                if ((this.OnlineStatusField.Equals(value) != true)) {
                    this.OnlineStatusField = value;
                    this.RaisePropertyChanged("OnlineStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.CustomerService.Framework.UserService.UserInfoType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfoType", Namespace="http://schemas.datacontract.org/2004/07/Client.Service.DataContract")]
    public enum UserInfoType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        上级 = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        下级 = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        用户 = 201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        客服 = 301,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IOfficialUserService")]
    public interface IOfficialUserService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOfficialUserService/SetIn", ReplyAction="http://tempuri.org/IOfficialUserService/SetInResponse")]
        System.IAsyncResult BeginSetIn(string username, string password, Client.CustomerService.Framework.UserService.UserOnlineStatus onlineStatus, System.AsyncCallback callback, object asyncState);
        
        Client.CustomerService.Framework.UserService.OperatingResultOfstring EndSetIn(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOfficialUserService/ChangeOnlineStatus", ReplyAction="http://tempuri.org/IOfficialUserService/ChangeOnlineStatusResponse")]
        System.IAsyncResult BeginChangeOnlineStatus(string username, Client.CustomerService.Framework.UserService.UserOnlineStatus newOnlineStatus, System.AsyncCallback callback, object asyncState);
        
        Client.CustomerService.Framework.UserService.OperatingResult EndChangeOnlineStatus(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOfficialUserService/GetUsers", ReplyAction="http://tempuri.org/IOfficialUserService/GetUsersResponse")]
        System.IAsyncResult BeginGetUsers(System.AsyncCallback callback, object asyncState);
        
        Client.CustomerService.Framework.UserService.OperatingResultOfArrayOfUserInfoResult5O3_PPRz2 EndGetUsers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOfficialUserService/Heartbeat", ReplyAction="http://tempuri.org/IOfficialUserService/HeartbeatResponse")]
        System.IAsyncResult BeginHeartbeat(string username, System.AsyncCallback callback, object asyncState);
        
        Client.CustomerService.Framework.UserService.OperatingResult EndHeartbeat(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOfficialUserServiceChannel : Client.CustomerService.Framework.UserService.IOfficialUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SetInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SetInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client.CustomerService.Framework.UserService.OperatingResultOfstring Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client.CustomerService.Framework.UserService.OperatingResultOfstring)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChangeOnlineStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ChangeOnlineStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client.CustomerService.Framework.UserService.OperatingResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client.CustomerService.Framework.UserService.OperatingResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client.CustomerService.Framework.UserService.OperatingResultOfArrayOfUserInfoResult5O3_PPRz2 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client.CustomerService.Framework.UserService.OperatingResultOfArrayOfUserInfoResult5O3_PPRz2)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeartbeatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HeartbeatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client.CustomerService.Framework.UserService.OperatingResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client.CustomerService.Framework.UserService.OperatingResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OfficialUserServiceClient : System.ServiceModel.ClientBase<Client.CustomerService.Framework.UserService.IOfficialUserService>, Client.CustomerService.Framework.UserService.IOfficialUserService {
        
        private BeginOperationDelegate onBeginSetInDelegate;
        
        private EndOperationDelegate onEndSetInDelegate;
        
        private System.Threading.SendOrPostCallback onSetInCompletedDelegate;
        
        private BeginOperationDelegate onBeginChangeOnlineStatusDelegate;
        
        private EndOperationDelegate onEndChangeOnlineStatusDelegate;
        
        private System.Threading.SendOrPostCallback onChangeOnlineStatusCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUsersDelegate;
        
        private EndOperationDelegate onEndGetUsersDelegate;
        
        private System.Threading.SendOrPostCallback onGetUsersCompletedDelegate;
        
        private BeginOperationDelegate onBeginHeartbeatDelegate;
        
        private EndOperationDelegate onEndHeartbeatDelegate;
        
        private System.Threading.SendOrPostCallback onHeartbeatCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public OfficialUserServiceClient() {
        }
        
        public OfficialUserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfficialUserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfficialUserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfficialUserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<SetInCompletedEventArgs> SetInCompleted;
        
        public event System.EventHandler<ChangeOnlineStatusCompletedEventArgs> ChangeOnlineStatusCompleted;
        
        public event System.EventHandler<GetUsersCompletedEventArgs> GetUsersCompleted;
        
        public event System.EventHandler<HeartbeatCompletedEventArgs> HeartbeatCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client.CustomerService.Framework.UserService.IOfficialUserService.BeginSetIn(string username, string password, Client.CustomerService.Framework.UserService.UserOnlineStatus onlineStatus, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetIn(username, password, onlineStatus, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.CustomerService.Framework.UserService.OperatingResultOfstring Client.CustomerService.Framework.UserService.IOfficialUserService.EndSetIn(System.IAsyncResult result) {
            return base.Channel.EndSetIn(result);
        }
        
        private System.IAsyncResult OnBeginSetIn(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            Client.CustomerService.Framework.UserService.UserOnlineStatus onlineStatus = ((Client.CustomerService.Framework.UserService.UserOnlineStatus)(inValues[2]));
            return ((Client.CustomerService.Framework.UserService.IOfficialUserService)(this)).BeginSetIn(username, password, onlineStatus, callback, asyncState);
        }
        
        private object[] OnEndSetIn(System.IAsyncResult result) {
            Client.CustomerService.Framework.UserService.OperatingResultOfstring retVal = ((Client.CustomerService.Framework.UserService.IOfficialUserService)(this)).EndSetIn(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSetInCompleted(object state) {
            if ((this.SetInCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetInCompleted(this, new SetInCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetInAsync(string username, string password, Client.CustomerService.Framework.UserService.UserOnlineStatus onlineStatus) {
            this.SetInAsync(username, password, onlineStatus, null);
        }
        
        public void SetInAsync(string username, string password, Client.CustomerService.Framework.UserService.UserOnlineStatus onlineStatus, object userState) {
            if ((this.onBeginSetInDelegate == null)) {
                this.onBeginSetInDelegate = new BeginOperationDelegate(this.OnBeginSetIn);
            }
            if ((this.onEndSetInDelegate == null)) {
                this.onEndSetInDelegate = new EndOperationDelegate(this.OnEndSetIn);
            }
            if ((this.onSetInCompletedDelegate == null)) {
                this.onSetInCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetInCompleted);
            }
            base.InvokeAsync(this.onBeginSetInDelegate, new object[] {
                        username,
                        password,
                        onlineStatus}, this.onEndSetInDelegate, this.onSetInCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client.CustomerService.Framework.UserService.IOfficialUserService.BeginChangeOnlineStatus(string username, Client.CustomerService.Framework.UserService.UserOnlineStatus newOnlineStatus, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChangeOnlineStatus(username, newOnlineStatus, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.CustomerService.Framework.UserService.OperatingResult Client.CustomerService.Framework.UserService.IOfficialUserService.EndChangeOnlineStatus(System.IAsyncResult result) {
            return base.Channel.EndChangeOnlineStatus(result);
        }
        
        private System.IAsyncResult OnBeginChangeOnlineStatus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            Client.CustomerService.Framework.UserService.UserOnlineStatus newOnlineStatus = ((Client.CustomerService.Framework.UserService.UserOnlineStatus)(inValues[1]));
            return ((Client.CustomerService.Framework.UserService.IOfficialUserService)(this)).BeginChangeOnlineStatus(username, newOnlineStatus, callback, asyncState);
        }
        
        private object[] OnEndChangeOnlineStatus(System.IAsyncResult result) {
            Client.CustomerService.Framework.UserService.OperatingResult retVal = ((Client.CustomerService.Framework.UserService.IOfficialUserService)(this)).EndChangeOnlineStatus(result);
            return new object[] {
                    retVal};
        }
        
        private void OnChangeOnlineStatusCompleted(object state) {
            if ((this.ChangeOnlineStatusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChangeOnlineStatusCompleted(this, new ChangeOnlineStatusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChangeOnlineStatusAsync(string username, Client.CustomerService.Framework.UserService.UserOnlineStatus newOnlineStatus) {
            this.ChangeOnlineStatusAsync(username, newOnlineStatus, null);
        }
        
        public void ChangeOnlineStatusAsync(string username, Client.CustomerService.Framework.UserService.UserOnlineStatus newOnlineStatus, object userState) {
            if ((this.onBeginChangeOnlineStatusDelegate == null)) {
                this.onBeginChangeOnlineStatusDelegate = new BeginOperationDelegate(this.OnBeginChangeOnlineStatus);
            }
            if ((this.onEndChangeOnlineStatusDelegate == null)) {
                this.onEndChangeOnlineStatusDelegate = new EndOperationDelegate(this.OnEndChangeOnlineStatus);
            }
            if ((this.onChangeOnlineStatusCompletedDelegate == null)) {
                this.onChangeOnlineStatusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChangeOnlineStatusCompleted);
            }
            base.InvokeAsync(this.onBeginChangeOnlineStatusDelegate, new object[] {
                        username,
                        newOnlineStatus}, this.onEndChangeOnlineStatusDelegate, this.onChangeOnlineStatusCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client.CustomerService.Framework.UserService.IOfficialUserService.BeginGetUsers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUsers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.CustomerService.Framework.UserService.OperatingResultOfArrayOfUserInfoResult5O3_PPRz2 Client.CustomerService.Framework.UserService.IOfficialUserService.EndGetUsers(System.IAsyncResult result) {
            return base.Channel.EndGetUsers(result);
        }
        
        private System.IAsyncResult OnBeginGetUsers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Client.CustomerService.Framework.UserService.IOfficialUserService)(this)).BeginGetUsers(callback, asyncState);
        }
        
        private object[] OnEndGetUsers(System.IAsyncResult result) {
            Client.CustomerService.Framework.UserService.OperatingResultOfArrayOfUserInfoResult5O3_PPRz2 retVal = ((Client.CustomerService.Framework.UserService.IOfficialUserService)(this)).EndGetUsers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUsersCompleted(object state) {
            if ((this.GetUsersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUsersCompleted(this, new GetUsersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUsersAsync() {
            this.GetUsersAsync(null);
        }
        
        public void GetUsersAsync(object userState) {
            if ((this.onBeginGetUsersDelegate == null)) {
                this.onBeginGetUsersDelegate = new BeginOperationDelegate(this.OnBeginGetUsers);
            }
            if ((this.onEndGetUsersDelegate == null)) {
                this.onEndGetUsersDelegate = new EndOperationDelegate(this.OnEndGetUsers);
            }
            if ((this.onGetUsersCompletedDelegate == null)) {
                this.onGetUsersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUsersCompleted);
            }
            base.InvokeAsync(this.onBeginGetUsersDelegate, null, this.onEndGetUsersDelegate, this.onGetUsersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client.CustomerService.Framework.UserService.IOfficialUserService.BeginHeartbeat(string username, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHeartbeat(username, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.CustomerService.Framework.UserService.OperatingResult Client.CustomerService.Framework.UserService.IOfficialUserService.EndHeartbeat(System.IAsyncResult result) {
            return base.Channel.EndHeartbeat(result);
        }
        
        private System.IAsyncResult OnBeginHeartbeat(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            return ((Client.CustomerService.Framework.UserService.IOfficialUserService)(this)).BeginHeartbeat(username, callback, asyncState);
        }
        
        private object[] OnEndHeartbeat(System.IAsyncResult result) {
            Client.CustomerService.Framework.UserService.OperatingResult retVal = ((Client.CustomerService.Framework.UserService.IOfficialUserService)(this)).EndHeartbeat(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHeartbeatCompleted(object state) {
            if ((this.HeartbeatCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HeartbeatCompleted(this, new HeartbeatCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HeartbeatAsync(string username) {
            this.HeartbeatAsync(username, null);
        }
        
        public void HeartbeatAsync(string username, object userState) {
            if ((this.onBeginHeartbeatDelegate == null)) {
                this.onBeginHeartbeatDelegate = new BeginOperationDelegate(this.OnBeginHeartbeat);
            }
            if ((this.onEndHeartbeatDelegate == null)) {
                this.onEndHeartbeatDelegate = new EndOperationDelegate(this.OnEndHeartbeat);
            }
            if ((this.onHeartbeatCompletedDelegate == null)) {
                this.onHeartbeatCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHeartbeatCompleted);
            }
            base.InvokeAsync(this.onBeginHeartbeatDelegate, new object[] {
                        username}, this.onEndHeartbeatDelegate, this.onHeartbeatCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Client.CustomerService.Framework.UserService.IOfficialUserService CreateChannel() {
            return new OfficialUserServiceClientChannel(this);
        }
        
        private class OfficialUserServiceClientChannel : ChannelBase<Client.CustomerService.Framework.UserService.IOfficialUserService>, Client.CustomerService.Framework.UserService.IOfficialUserService {
            
            public OfficialUserServiceClientChannel(System.ServiceModel.ClientBase<Client.CustomerService.Framework.UserService.IOfficialUserService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSetIn(string username, string password, Client.CustomerService.Framework.UserService.UserOnlineStatus onlineStatus, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = username;
                _args[1] = password;
                _args[2] = onlineStatus;
                System.IAsyncResult _result = base.BeginInvoke("SetIn", _args, callback, asyncState);
                return _result;
            }
            
            public Client.CustomerService.Framework.UserService.OperatingResultOfstring EndSetIn(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client.CustomerService.Framework.UserService.OperatingResultOfstring _result = ((Client.CustomerService.Framework.UserService.OperatingResultOfstring)(base.EndInvoke("SetIn", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginChangeOnlineStatus(string username, Client.CustomerService.Framework.UserService.UserOnlineStatus newOnlineStatus, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = username;
                _args[1] = newOnlineStatus;
                System.IAsyncResult _result = base.BeginInvoke("ChangeOnlineStatus", _args, callback, asyncState);
                return _result;
            }
            
            public Client.CustomerService.Framework.UserService.OperatingResult EndChangeOnlineStatus(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client.CustomerService.Framework.UserService.OperatingResult _result = ((Client.CustomerService.Framework.UserService.OperatingResult)(base.EndInvoke("ChangeOnlineStatus", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUsers(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetUsers", _args, callback, asyncState);
                return _result;
            }
            
            public Client.CustomerService.Framework.UserService.OperatingResultOfArrayOfUserInfoResult5O3_PPRz2 EndGetUsers(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client.CustomerService.Framework.UserService.OperatingResultOfArrayOfUserInfoResult5O3_PPRz2 _result = ((Client.CustomerService.Framework.UserService.OperatingResultOfArrayOfUserInfoResult5O3_PPRz2)(base.EndInvoke("GetUsers", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHeartbeat(string username, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = username;
                System.IAsyncResult _result = base.BeginInvoke("Heartbeat", _args, callback, asyncState);
                return _result;
            }
            
            public Client.CustomerService.Framework.UserService.OperatingResult EndHeartbeat(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client.CustomerService.Framework.UserService.OperatingResult _result = ((Client.CustomerService.Framework.UserService.OperatingResult)(base.EndInvoke("Heartbeat", _args, result)));
                return _result;
            }
        }
    }
}
