//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18051
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace ToClient.MessageService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatingResult", Namespace="http://schemas.datacontract.org/2004/07/Client.Service.DataContract")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToClient.MessageService.OperatingResultOfArrayOfMessageResult5O3_PPRz2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToClient.MessageService.OperatingResultOfPaginationListOfMessageResult5O3_PPRz25O3_PPRz2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ToClient.MessageService.OperatingResultOfArrayOfUnreadMessageCountResult5O3_PPRz2))]
    public partial class OperatingResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatingResultOfArrayOfMessageResult5O3_PPRz2", Namespace="http://schemas.datacontract.org/2004/07/Client.Service.DataContract")]
    public partial class OperatingResultOfArrayOfMessageResult5O3_PPRz2 : ToClient.MessageService.OperatingResult {
        
        private System.Collections.Generic.List<ToClient.MessageService.MessageResult> ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ToClient.MessageService.MessageResult> Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatingResultOfPaginationListOfMessageResult5O3_PPRz25O3_PPRz2", Namespace="http://schemas.datacontract.org/2004/07/Client.Service.DataContract")]
    public partial class OperatingResultOfPaginationListOfMessageResult5O3_PPRz25O3_PPRz2 : ToClient.MessageService.OperatingResult {
        
        private ToClient.MessageService.PaginationListOfMessageResult5O3_PPRz2 ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ToClient.MessageService.PaginationListOfMessageResult5O3_PPRz2 Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatingResultOfArrayOfUnreadMessageCountResult5O3_PPRz2", Namespace="http://schemas.datacontract.org/2004/07/Client.Service.DataContract")]
    public partial class OperatingResultOfArrayOfUnreadMessageCountResult5O3_PPRz2 : ToClient.MessageService.OperatingResult {
        
        private System.Collections.Generic.List<ToClient.MessageService.UnreadMessageCountResult> ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ToClient.MessageService.UnreadMessageCountResult> Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnreadMessageCountResult", Namespace="http://schemas.datacontract.org/2004/07/Client.Service.DataContract")]
    public partial class UnreadMessageCountResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CountField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageResult", Namespace="http://schemas.datacontract.org/2004/07/Client.Service.DataContract")]
    public partial class MessageResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ContentField;
        
        private string FromField;
        
        private bool IsOfficialField;
        
        private bool IsSelfField;
        
        private System.DateTime SendTimeField;
        
        private string ToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOfficial {
            get {
                return this.IsOfficialField;
            }
            set {
                if ((this.IsOfficialField.Equals(value) != true)) {
                    this.IsOfficialField = value;
                    this.RaisePropertyChanged("IsOfficial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelf {
            get {
                return this.IsSelfField;
            }
            set {
                if ((this.IsSelfField.Equals(value) != true)) {
                    this.IsSelfField = value;
                    this.RaisePropertyChanged("IsSelf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendTime {
            get {
                return this.SendTimeField;
            }
            set {
                if ((this.SendTimeField.Equals(value) != true)) {
                    this.SendTimeField = value;
                    this.RaisePropertyChanged("SendTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaginationListOfMessageResult5O3_PPRz2", Namespace="http://schemas.datacontract.org/2004/07/Client.Service.DataContract")]
    public partial class PaginationListOfMessageResult5O3_PPRz2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<ToClient.MessageService.MessageResult> ContentField;
        
        private int PageIndexField;
        
        private int PageSizeField;
        
        private int TotalField;
        
        private int TotalOfPageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ToClient.MessageService.MessageResult> Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalOfPage {
            get {
                return this.TotalOfPageField;
            }
            set {
                if ((this.TotalOfPageField.Equals(value) != true)) {
                    this.TotalOfPageField = value;
                    this.RaisePropertyChanged("TotalOfPage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMessageImport", Namespace="http://schemas.datacontract.org/2004/07/Client.Service.DataContract")]
    public partial class SendMessageImport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ContentField;
        
        private string FromField;
        
        private string ToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageService.IMessageService")]
    public interface IMessageService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMessageService/GetCountOfUnreadMessages", ReplyAction="http://tempuri.org/IMessageService/GetCountOfUnreadMessagesResponse")]
        System.IAsyncResult BeginGetCountOfUnreadMessages(string username, System.AsyncCallback callback, object asyncState);
        
        ToClient.MessageService.OperatingResultOfArrayOfUnreadMessageCountResult5O3_PPRz2 EndGetCountOfUnreadMessages(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMessageService/GetUnreadMessages", ReplyAction="http://tempuri.org/IMessageService/GetUnreadMessagesResponse")]
        System.IAsyncResult BeginGetUnreadMessages(string _from, string _to, System.AsyncCallback callback, object asyncState);
        
        ToClient.MessageService.OperatingResultOfArrayOfMessageResult5O3_PPRz2 EndGetUnreadMessages(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMessageService/GetMessages", ReplyAction="http://tempuri.org/IMessageService/GetMessagesResponse")]
        System.IAsyncResult BeginGetMessages(string _from, string _to, int page, int pageSize, System.AsyncCallback callback, object asyncState);
        
        ToClient.MessageService.OperatingResultOfPaginationListOfMessageResult5O3_PPRz25O3_PPRz2 EndGetMessages(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMessageService/Send", ReplyAction="http://tempuri.org/IMessageService/SendResponse")]
        System.IAsyncResult BeginSend(ToClient.MessageService.SendMessageImport import, System.AsyncCallback callback, object asyncState);
        
        ToClient.MessageService.OperatingResult EndSend(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageServiceChannel : ToClient.MessageService.IMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCountOfUnreadMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCountOfUnreadMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ToClient.MessageService.OperatingResultOfArrayOfUnreadMessageCountResult5O3_PPRz2 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ToClient.MessageService.OperatingResultOfArrayOfUnreadMessageCountResult5O3_PPRz2)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUnreadMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUnreadMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ToClient.MessageService.OperatingResultOfArrayOfMessageResult5O3_PPRz2 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ToClient.MessageService.OperatingResultOfArrayOfMessageResult5O3_PPRz2)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ToClient.MessageService.OperatingResultOfPaginationListOfMessageResult5O3_PPRz25O3_PPRz2 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ToClient.MessageService.OperatingResultOfPaginationListOfMessageResult5O3_PPRz25O3_PPRz2)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ToClient.MessageService.OperatingResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ToClient.MessageService.OperatingResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceClient : System.ServiceModel.ClientBase<ToClient.MessageService.IMessageService>, ToClient.MessageService.IMessageService {
        
        private BeginOperationDelegate onBeginGetCountOfUnreadMessagesDelegate;
        
        private EndOperationDelegate onEndGetCountOfUnreadMessagesDelegate;
        
        private System.Threading.SendOrPostCallback onGetCountOfUnreadMessagesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUnreadMessagesDelegate;
        
        private EndOperationDelegate onEndGetUnreadMessagesDelegate;
        
        private System.Threading.SendOrPostCallback onGetUnreadMessagesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMessagesDelegate;
        
        private EndOperationDelegate onEndGetMessagesDelegate;
        
        private System.Threading.SendOrPostCallback onGetMessagesCompletedDelegate;
        
        private BeginOperationDelegate onBeginSendDelegate;
        
        private EndOperationDelegate onEndSendDelegate;
        
        private System.Threading.SendOrPostCallback onSendCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public MessageServiceClient() {
        }
        
        public MessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<GetCountOfUnreadMessagesCompletedEventArgs> GetCountOfUnreadMessagesCompleted;
        
        public event System.EventHandler<GetUnreadMessagesCompletedEventArgs> GetUnreadMessagesCompleted;
        
        public event System.EventHandler<GetMessagesCompletedEventArgs> GetMessagesCompleted;
        
        public event System.EventHandler<SendCompletedEventArgs> SendCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ToClient.MessageService.IMessageService.BeginGetCountOfUnreadMessages(string username, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCountOfUnreadMessages(username, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ToClient.MessageService.OperatingResultOfArrayOfUnreadMessageCountResult5O3_PPRz2 ToClient.MessageService.IMessageService.EndGetCountOfUnreadMessages(System.IAsyncResult result) {
            return base.Channel.EndGetCountOfUnreadMessages(result);
        }
        
        private System.IAsyncResult OnBeginGetCountOfUnreadMessages(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            return ((ToClient.MessageService.IMessageService)(this)).BeginGetCountOfUnreadMessages(username, callback, asyncState);
        }
        
        private object[] OnEndGetCountOfUnreadMessages(System.IAsyncResult result) {
            ToClient.MessageService.OperatingResultOfArrayOfUnreadMessageCountResult5O3_PPRz2 retVal = ((ToClient.MessageService.IMessageService)(this)).EndGetCountOfUnreadMessages(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCountOfUnreadMessagesCompleted(object state) {
            if ((this.GetCountOfUnreadMessagesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCountOfUnreadMessagesCompleted(this, new GetCountOfUnreadMessagesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCountOfUnreadMessagesAsync(string username) {
            this.GetCountOfUnreadMessagesAsync(username, null);
        }
        
        public void GetCountOfUnreadMessagesAsync(string username, object userState) {
            if ((this.onBeginGetCountOfUnreadMessagesDelegate == null)) {
                this.onBeginGetCountOfUnreadMessagesDelegate = new BeginOperationDelegate(this.OnBeginGetCountOfUnreadMessages);
            }
            if ((this.onEndGetCountOfUnreadMessagesDelegate == null)) {
                this.onEndGetCountOfUnreadMessagesDelegate = new EndOperationDelegate(this.OnEndGetCountOfUnreadMessages);
            }
            if ((this.onGetCountOfUnreadMessagesCompletedDelegate == null)) {
                this.onGetCountOfUnreadMessagesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCountOfUnreadMessagesCompleted);
            }
            base.InvokeAsync(this.onBeginGetCountOfUnreadMessagesDelegate, new object[] {
                        username}, this.onEndGetCountOfUnreadMessagesDelegate, this.onGetCountOfUnreadMessagesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ToClient.MessageService.IMessageService.BeginGetUnreadMessages(string _from, string _to, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUnreadMessages(_from, _to, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ToClient.MessageService.OperatingResultOfArrayOfMessageResult5O3_PPRz2 ToClient.MessageService.IMessageService.EndGetUnreadMessages(System.IAsyncResult result) {
            return base.Channel.EndGetUnreadMessages(result);
        }
        
        private System.IAsyncResult OnBeginGetUnreadMessages(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string _from = ((string)(inValues[0]));
            string _to = ((string)(inValues[1]));
            return ((ToClient.MessageService.IMessageService)(this)).BeginGetUnreadMessages(_from, _to, callback, asyncState);
        }
        
        private object[] OnEndGetUnreadMessages(System.IAsyncResult result) {
            ToClient.MessageService.OperatingResultOfArrayOfMessageResult5O3_PPRz2 retVal = ((ToClient.MessageService.IMessageService)(this)).EndGetUnreadMessages(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUnreadMessagesCompleted(object state) {
            if ((this.GetUnreadMessagesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUnreadMessagesCompleted(this, new GetUnreadMessagesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUnreadMessagesAsync(string _from, string _to) {
            this.GetUnreadMessagesAsync(_from, _to, null);
        }
        
        public void GetUnreadMessagesAsync(string _from, string _to, object userState) {
            if ((this.onBeginGetUnreadMessagesDelegate == null)) {
                this.onBeginGetUnreadMessagesDelegate = new BeginOperationDelegate(this.OnBeginGetUnreadMessages);
            }
            if ((this.onEndGetUnreadMessagesDelegate == null)) {
                this.onEndGetUnreadMessagesDelegate = new EndOperationDelegate(this.OnEndGetUnreadMessages);
            }
            if ((this.onGetUnreadMessagesCompletedDelegate == null)) {
                this.onGetUnreadMessagesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUnreadMessagesCompleted);
            }
            base.InvokeAsync(this.onBeginGetUnreadMessagesDelegate, new object[] {
                        _from,
                        _to}, this.onEndGetUnreadMessagesDelegate, this.onGetUnreadMessagesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ToClient.MessageService.IMessageService.BeginGetMessages(string _from, string _to, int page, int pageSize, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMessages(_from, _to, page, pageSize, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ToClient.MessageService.OperatingResultOfPaginationListOfMessageResult5O3_PPRz25O3_PPRz2 ToClient.MessageService.IMessageService.EndGetMessages(System.IAsyncResult result) {
            return base.Channel.EndGetMessages(result);
        }
        
        private System.IAsyncResult OnBeginGetMessages(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string _from = ((string)(inValues[0]));
            string _to = ((string)(inValues[1]));
            int page = ((int)(inValues[2]));
            int pageSize = ((int)(inValues[3]));
            return ((ToClient.MessageService.IMessageService)(this)).BeginGetMessages(_from, _to, page, pageSize, callback, asyncState);
        }
        
        private object[] OnEndGetMessages(System.IAsyncResult result) {
            ToClient.MessageService.OperatingResultOfPaginationListOfMessageResult5O3_PPRz25O3_PPRz2 retVal = ((ToClient.MessageService.IMessageService)(this)).EndGetMessages(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMessagesCompleted(object state) {
            if ((this.GetMessagesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMessagesCompleted(this, new GetMessagesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMessagesAsync(string _from, string _to, int page, int pageSize) {
            this.GetMessagesAsync(_from, _to, page, pageSize, null);
        }
        
        public void GetMessagesAsync(string _from, string _to, int page, int pageSize, object userState) {
            if ((this.onBeginGetMessagesDelegate == null)) {
                this.onBeginGetMessagesDelegate = new BeginOperationDelegate(this.OnBeginGetMessages);
            }
            if ((this.onEndGetMessagesDelegate == null)) {
                this.onEndGetMessagesDelegate = new EndOperationDelegate(this.OnEndGetMessages);
            }
            if ((this.onGetMessagesCompletedDelegate == null)) {
                this.onGetMessagesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMessagesCompleted);
            }
            base.InvokeAsync(this.onBeginGetMessagesDelegate, new object[] {
                        _from,
                        _to,
                        page,
                        pageSize}, this.onEndGetMessagesDelegate, this.onGetMessagesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ToClient.MessageService.IMessageService.BeginSend(ToClient.MessageService.SendMessageImport import, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSend(import, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ToClient.MessageService.OperatingResult ToClient.MessageService.IMessageService.EndSend(System.IAsyncResult result) {
            return base.Channel.EndSend(result);
        }
        
        private System.IAsyncResult OnBeginSend(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ToClient.MessageService.SendMessageImport import = ((ToClient.MessageService.SendMessageImport)(inValues[0]));
            return ((ToClient.MessageService.IMessageService)(this)).BeginSend(import, callback, asyncState);
        }
        
        private object[] OnEndSend(System.IAsyncResult result) {
            ToClient.MessageService.OperatingResult retVal = ((ToClient.MessageService.IMessageService)(this)).EndSend(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSendCompleted(object state) {
            if ((this.SendCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendCompleted(this, new SendCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendAsync(ToClient.MessageService.SendMessageImport import) {
            this.SendAsync(import, null);
        }
        
        public void SendAsync(ToClient.MessageService.SendMessageImport import, object userState) {
            if ((this.onBeginSendDelegate == null)) {
                this.onBeginSendDelegate = new BeginOperationDelegate(this.OnBeginSend);
            }
            if ((this.onEndSendDelegate == null)) {
                this.onEndSendDelegate = new EndOperationDelegate(this.OnEndSend);
            }
            if ((this.onSendCompletedDelegate == null)) {
                this.onSendCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendCompleted);
            }
            base.InvokeAsync(this.onBeginSendDelegate, new object[] {
                        import}, this.onEndSendDelegate, this.onSendCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ToClient.MessageService.IMessageService CreateChannel() {
            return new MessageServiceClientChannel(this);
        }
        
        private class MessageServiceClientChannel : ChannelBase<ToClient.MessageService.IMessageService>, ToClient.MessageService.IMessageService {
            
            public MessageServiceClientChannel(System.ServiceModel.ClientBase<ToClient.MessageService.IMessageService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetCountOfUnreadMessages(string username, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = username;
                System.IAsyncResult _result = base.BeginInvoke("GetCountOfUnreadMessages", _args, callback, asyncState);
                return _result;
            }
            
            public ToClient.MessageService.OperatingResultOfArrayOfUnreadMessageCountResult5O3_PPRz2 EndGetCountOfUnreadMessages(System.IAsyncResult result) {
                object[] _args = new object[0];
                ToClient.MessageService.OperatingResultOfArrayOfUnreadMessageCountResult5O3_PPRz2 _result = ((ToClient.MessageService.OperatingResultOfArrayOfUnreadMessageCountResult5O3_PPRz2)(base.EndInvoke("GetCountOfUnreadMessages", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUnreadMessages(string _from, string _to, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = _from;
                _args[1] = _to;
                System.IAsyncResult _result = base.BeginInvoke("GetUnreadMessages", _args, callback, asyncState);
                return _result;
            }
            
            public ToClient.MessageService.OperatingResultOfArrayOfMessageResult5O3_PPRz2 EndGetUnreadMessages(System.IAsyncResult result) {
                object[] _args = new object[0];
                ToClient.MessageService.OperatingResultOfArrayOfMessageResult5O3_PPRz2 _result = ((ToClient.MessageService.OperatingResultOfArrayOfMessageResult5O3_PPRz2)(base.EndInvoke("GetUnreadMessages", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMessages(string _from, string _to, int page, int pageSize, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = _from;
                _args[1] = _to;
                _args[2] = page;
                _args[3] = pageSize;
                System.IAsyncResult _result = base.BeginInvoke("GetMessages", _args, callback, asyncState);
                return _result;
            }
            
            public ToClient.MessageService.OperatingResultOfPaginationListOfMessageResult5O3_PPRz25O3_PPRz2 EndGetMessages(System.IAsyncResult result) {
                object[] _args = new object[0];
                ToClient.MessageService.OperatingResultOfPaginationListOfMessageResult5O3_PPRz25O3_PPRz2 _result = ((ToClient.MessageService.OperatingResultOfPaginationListOfMessageResult5O3_PPRz25O3_PPRz2)(base.EndInvoke("GetMessages", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSend(ToClient.MessageService.SendMessageImport import, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = import;
                System.IAsyncResult _result = base.BeginInvoke("Send", _args, callback, asyncState);
                return _result;
            }
            
            public ToClient.MessageService.OperatingResult EndSend(System.IAsyncResult result) {
                object[] _args = new object[0];
                ToClient.MessageService.OperatingResult _result = ((ToClient.MessageService.OperatingResult)(base.EndInvoke("Send", _args, result)));
                return _result;
            }
        }
    }
}
