<?xml version="1.0" encoding="utf-8"?><Database Name="CnLotteryDbs" Class="MainDatadbmlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MAGICVR-PC;Initial Catalog=CnLotteryDbs;Persist Security Info=True;User ID=sa" SettingsObjectName="Client.Model.Properties.Settings" SettingsPropertyName="CnLotteryDbsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserInfo" Member="UserInfo">
    <Type Name="UserInfo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UserPwd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ParentUID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RegTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsOnline" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastLoginTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Bonus" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="FullPath" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CarrierBankCardNo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MobilePhoneNum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="BonusToParent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QQ" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CanMoneyToLower" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FreezingLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RiseBonus" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RankID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nickname" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LastUpRankTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsRankEnable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxBonus" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DishScore" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>